#!/usr/bin/env python
import fire
import os
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi.training import train_auto_encoder

if __name__ == '__main__':
    fire.Fire(train_auto_encoder)

# Sample args:
# --datasets "['CIRCLES']" --n_gpus 4 --n_nodes 1 --n_workers 4 --use_logger True
